### ISSUE TITLE
Main Search Box and drop down background color stuck at white

### ISSUE THREAD

**Issue by xrolfex** [Nass-O/DarkSearch#9]
These sections need to have the ` !important` added so they override properly.

  .sbib_a, .sbibod {
        background: #222;
    }
    .sbib_a:hover, .sbibod:hover {
        background: #222;
    }

    /* New dropdown */
    .sbsb_a {
        background: #222;
    }

**Comment by franklinyu** [comment]
@xrolfex Your Markdown is broken.
